spring:
  datasource:
    url: ${LOCAL_DB_URL:jdbc:mysql://localhost:3306/bookripple}
    username: ${LOCAL_DB_USER:root}
    password: ${LOCAL_DB_PW}
    driver-class-name: ${LOCAL_DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    default-encoding: UTF-8

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:1800000}

logging:
  level:
    org.hibernate.SQL: DEBUG